### ISSUE TITLE
Add a -t option for specifying custom number of threads per process

### ISSUE THREAD

**Issue by excalibur-kvrv** [excalibur-kvrv/m3u8-dl#36]
**Is your feature request related to a problem? Please describe.**
Adding a cli -t option will user to customize and scale the download speed as per their needs

**Describe the solution you'd like**
We can add a cli option -t that on invokation will look like `m3u8-dl <url-of-playlist> -t 8` this would mean starting the download processes with 8 threads per process, so if there are 4 download processes there will be a total of 32 threads.

**Comment by OliverVermeulen** [comment]
I'm gonna take a look at this.
