### ISSUE TITLE
Add a custom -f option to read a m3u8 playlist from a file if a .m3u8 playlist file is available

### ISSUE THREAD

**Issue by excalibur-kvrv** [excalibur-kvrv/m3u8-dl#38]
**Is your feature request related to a problem? Please describe.**
Addition of a -f option will allow users to read the m3u8 playlist from a file if a file is available in the local filesystem, this will allow users to pass in the file path if the playlist has already been downloaded.

**Describe the solution you'd like**
We can add a cli option -f that on invokation will look like `m3u8-dl -f <relative/absolute path-of-playlist>` this would allow users to read the playlist from a file, all other functionality will work AS-IS.

**Additional context**
The python library m3u8 maybe used to accomplish this task https://pypi.org/project/m3u8/

**Comment by lcd1232** [comment]
Can I take this issue?

**Comment by lcd1232** [comment]
I think it would be better if we just check is it URL or file path. If its file path, then just open it.

**Comment by excalibur-kvrv** [comment]
Yeah feel free to pick it up @lcd1232

**Comment by excalibur-kvrv** [comment]
> I think it would be better if we just check is it URL or file path. If its file path, then just open it.

Sounds good.
