### ISSUE TITLE
Use this issue to ask questions on installation or any other installation related issues.

### ISSUE THREAD

**Issue by excalibur-kvrv** [excalibur-kvrv/m3u8-dl#45]

**Comment by Nirvanatin** [comment]
How to pass on the key?

In my case: 
([Link](https://dramasq.com/day-and-night/1.html))

`m3u8-dl https://video.dious.cc/20200724/GmYb4Mmm/index.m3u8 output.ts`

**Comment by kevinrvaz** [comment]
what key?

**Comment by Nirvanatin** [comment]
AES-128 key
`#EXT-X-KEY:METHOD=AES-128,URI="https://ts1.lslkkyj.com/20200724/GmYb4Mmm/1000kb/hls/key.key"`
in the secondary [URL](https://video.dious.cc/20200724/GmYb4Mmm/1000kb/hls/index.m3u8).

**Comment by kevinrvaz** [comment]
This software dosen't support decrypting ts chunks yet. Can you raise this as an issue? ill look into adding this as a feature
