### ISSUE TITLE
Stream Reset error

### ISSUE THREAD

**Issue by chanduvardhan007** [excalibur-kvrv/m3u8-dl#8]
**Describe the bug**
While i am running the main.py file by taking fmovies link the download process,video handling process and producer process are getting started but suddenly the process is terminated due to stream reset error "hyper.http20.exceptions.StreamResetError: (Stream forcefully closed)".

**To Reproduce**
1. Go to online video streaming website "https://ww5.fmovie.sc/"
2. Play online streaming video then right click on the page and click on inspect.
3. Go to Network option and got to XHR, u can see several names.
4.Click on .m3u8 extension link and on the right scroll down to copy the request headers to header.txt file in the project and save it
3. Scroll up and copy the url and run > python main.py url -c

**Expected behavior**
what actually happens if there is no bug is the parser will parse all the links and download the chunks of the video in m3u8 format and later it is converted into mp4 format and into a single video.

**Screenshots**
![Screenshot (81)](https://user-images.githubusercontent.com/48998677/87869112-c71eb580-c9ba-11ea-9d3e-5f565b09d2c1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 - Version Chrome: 83

**Comment by excalibur-kvrv** [comment]
After debugging the application, it appears the links are being parsed properly. This is an issue with one of the external libraries "hyper", two possible ways of fixing it is either wait till hyper adds support for latest version of "h2" library or wait till requests3 is released in which case hyper will no longer be required. I'll close this issue for now.

**Comment by excalibur-kvrv** [comment]
issue #9 will be used to solve this issue.
